name: IaC Checks

on:
  push:
  pull_request:

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Set up TFLint
      uses: terraform-linters/setup-tflint@v4

    - name: Terraform init (no backend)
      run: terraform init -backend=false -input=false -lock=false

    - name: Format Terraform
      run: terraform fmt -recursive -check

    - name: Validate Terraform
      run: terraform validate

    - name: TFLint init
      run: tflint --init

    - name: TFLint
      run: tflint -f compact

    - name: Checkov (Terraform)
      uses: bridgecrewio/checkov-action@v12
      with:
        framework: terraform
